FROM ubuntu 
MAINTAINER Pedro Gutiérrez <pedrogutierrez@mac.com>
RUN apt-get update
RUN apt-get install -y tar git curl vim wget dialog net-tools build-essential
RUN apt-get install -y python3 python3-dev python-distribute python3-pip
ADD . /app
RUN pip3 install -r /app/requirements.txt
WORKDIR /app
EXPOSE 4001 
ENTRYPOINT ["python3", "app.py"]
